sudo: required
services:
- docker
before_install:
- docker build -t michaelcalizzi/react-test -f ./client/Dockefile.dev ./client
script:
- docker run michaelcalizzi/react-test npm test -- --coverage
after_success:
- docker build -t michaelcalizzi/multi-client ./client
- docker build -t michaelcalizzi/multi-nginx ./nginx
- docker build -t michaelcalizzi/multi-server ./server
- docker build -t michaelcalizzi/multi-worker ./worker